name: "Tag and Export Bit Component"
description: "Tags and exports bit component"

inputs:
  bit-token:
    description: "Bit token to use for interaction with bit service"
    required: true

outputs:
  changes:
    description: "List of changes to output to Slack channel"

runs:
  using: docker
  image: docker://us-east1-docker.pkg.dev/parsley-artifacts/parsley-bit/bit-tag-export:latest
  args:
    - ${{ inputs.bit-token }}
