name: "Cucumber BDD Test/Export"
description: "Runs cucumber BDD tests and exports reports to x-ray"
inputs:
  project-id:
    description: "JIRA project ID to use for tests"
    required: true
  browser:
    description: "Browser engine to use with tests (chromium|firefox|webkit)"
    required: true
  record-video:
    description: "Record BDD test execution video (default:true)"
    required: false
    default: "true"
  node-version:
    description: "NodeJS version to use (default:lts/gallium)"
    required: false
    default: "lts/gallium"
  xray-client-id:
    description: "Xray client ID"
    required: true
  xray-client-secret:
    description: "Xray client secret"
    required: true
  github-token:
    description: "Github token for uploading artifacts etc."
    required: true

outputs:
  test_exec_key:
    description: "The key of the created test execution"
    value: ${{ steps.xray-import.outputs.testExecKey }}

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Cache node_modules
      uses: actions/cache@v3
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Cache Playwright
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/ms-playwright
        key: playwright-${{ hashFiles('package-lock.json') }}

    - name: Update Dependencies
      shell: bash
      run: npm run deps

    - name: Run BDD Test
      shell: bash
      continue-on-error: true
      env:
        BROWSER: ${{ inputs.browser }}
        RECORD_VIDEO: ${{ inputs.record-video }}
      run: npm run cucumber-test

    - name: Generate Cucumber Reports
      shell: bash
      env:
        BROWSER: ${{ inputs.browser }}
      run: |
        npm run pretty-cucumber-report
        npm run xray-cucumber-report

    - name: Github Annotation Report
      uses: deblockt/cucumber-report-annotations-action@v1.7
      with:
        name: Cucumber report ${{ inputs.browser }}
        access-token: ${{ inputs.github-token }}
        path: reports/cucumber-report.json

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: cucumber-report-${{ inputs.browser }}
        path: reports
        retention-days: 7

    # this action doesn't seem to work at all w/ cucumber combined JSON
    # - name: Import results to Xray
    #   uses: parsleyhealth/xray-action@main
    #   id: xray-import
    #   with:
    #     username: ${{ inputs.xray-client-id }}
    #     password: ${{ inputs.xray-client-secret }}
    #     testFormat: cucumber
    #     testPaths: "reports/*.json"
    #     #testExecKey: "TEST-1"
    #     projectKey: ${{ inputs.project-id }}

    - name: Get Xray Bearer Token
      id: xray
      shell: bash
      run: |
        echo "::set-output name=token::$(curl \
          -Ss \
          -H "Content-Type: application/json" \
          --data $(jq -Mcrn \
            --arg id ${{ inputs..xray-client-id }} \
            --arg sec ${{ inputs.xray-client-secret }} \
            '{ client_id: $id, client_secret: $sec }') \
            https://xray.cloud.getxray.app/api/v2/authenticate  \
          | tr -d '"' \
        )"

    - name: "Import Execution Result To Xray"
      shell: bash
      run: |
        curl \
          -Ss \
          -H "Content-Type: multipart/form-data" \
          -H "Authorization: Bearer ${{ steps.xray.outputs.token }}" \
          -F info=@./reports/issueFields.json \
          -F results=@./reports/cucumber-report.json \
          https://xray.cloud.getxray.app/api/v2/import/execution/cucumber/multipart
