name: "Flyway Migration"
description: "Run flyway database migration using cloud sql proxy"

inputs:
  flyway-command:
    description: "Command to issue to Flyway, ex. `-url=jdbc:postgresql://localhost:5432/api -user=api_user -schemas=api,public migrate`"
    required: true
  cloud-sql-instance:
    description: "CloudSQL instance connection string, ex. `parsley-development:us-east1:somedb=tcp:5432`"
    required: true
  migrations-dir:
    description: "Location of migration files relative from repository root"
    required: false
    default: ""
  retries:
    description: "Amount of times to retry Flyway command on failure"
    required: false
    default: "5"

runs:
  using: docker
  image: Dockerfile
  env:
    FLYWAY_COMMAND: ${{ inputs.flyway-command }}
    MIGRATIONS_DIR: ${{ inputs.migrations-dir }}
    CLOUD_SQL_INSTANCE: ${{ inputs.cloud-sql-instance }}
  args:
    - ${{ inputs.retries }}
