name: "Goose Migration"
description: "Run goose database migration using cloud sql proxy"

inputs:
  goose-command:
    description: "Command to issue to goose"
    required: true
  cloud-sql-instance:
    description: "CloudSQL instance connection string, ex. `parsley-development:us-east1:somedb=tcp:5432`"
    required: true
  migrations-dir:
    description: "Location of migration files relative from repository root"
    required: false
    default: ""
  retries:
    description: "Amount of times to retry goose command on failure"
    required: false
    default: "5"
  goose-version:
    description: "Version of goose to use (default: `latest`)"
    required: false
    default: "latest"

runs:
  using: docker
  image: Dockerfile
  env:
    GOOSE_COMMAND: -dir $GITHUB_WORKSPACE${{ inputs.migrations-dir }} ${{ inputs.goose-command }}
  args:
    - ${{ inputs.goose-version }}
    - ${{ inputs.cloud-sql-instance }}
    - ${{ inputs.retries }}
