name: "Tag and Export Bit Component"
description: "Tags and exports bit component"

inputs:
  parsley-bot-token:
    description: "PAT for parsleybot to commit back changes to `master` and bypass branch protection"
    required: true
  bit-token:
    description: "Bit token to use for interaction with bit service"
    required: true
  slack-channel-id:
    description: "Slack channel ID to post notification to"
    required: true
  slack-bot-token:
    description: "Slack bot token"
    required: true
  gcp-workload-id-provider:
    description: "GCP workload ID provider name"
    required: true
  gcp-workload-id-service-account-email:
    description: "GCP service account email to assume"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ inputs.parsley-bot-token }}

    - name: Run bit export
      uses: parsleyhealth/github-composite-actions/bit-tag-export/docker@main
      with:
        bit-token: ${{ inputs.bit-token }}

    - name: Commit update changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "update .bitmap with new component versions (automated). --skip-ci"
        commit_user_name: "parsleybot"
        commit_user_email: "parsleybot@parsleyhealth.com"

    - name: Send Slack notification
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ inputs.slack-bot-token }}
        channel_id: ${{ inputs.slack-channel-id }}
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "PH-Bit Bot",
              "text": "*Bit Component Updates*\n\n${{ env.BIT_CHANGES }}"
          }
