name: "Atlas Migration"
description: "Run atlas database migration using cloud sql proxy"

inputs:
  atlas-command:
    description: "Command to issue to Atlas"
    required: true
  cloud-sql-instance:
    description: "CloudSQL instance connection string, ex. `parsley-development:us-east1:somedb=tcp:5432`"
    required: false
    default: ""
  migrations-dir:
    description: "Location of migration files relative from repository root"
    required: false
    default: ""
  retries:
    description: "Amount of times to retry Atlas command on failure"
    required: false
    default: "5"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - shell: bash
      run: |
        docker run --rm --net=host arigaio/atlas ${{ inputs.atlas-command }
