#!/usr/bin/env bash
#
# Write a user-tier Gemini CLI policy that makes a review pass read-only.
#
# google-github-actions/run-gemini-cli invokes the CLI as `gemini --yolo`, and
# --yolo ships with a Default-tier (base priority 1) rule that allows every tool.
# Only a higher tier can take that back. Workspace-tier policies are currently
# non-functional upstream, so the policy has to land in the user tier, at
# ~/.gemini/policies/*.toml, which has base priority 4.
#
# Within the user tier the highest `priority` wins, so the ordering below is:
#   900  deny write_file and replace outright
#   500  allow the specific shell commands a review needs
#   100  deny every other shell command
set -euo pipefail

POLICY_DIR="${HOME}/.gemini/policies"
POLICY_FILE="${POLICY_DIR}/pr-review.toml"
mkdir -p "${POLICY_DIR}"

# Commands a review pass may run. `commandPrefix` matches on a prefix, so the
# test command still matches once the model appends specific test files to it.
allowed_prefixes() {
  printf '%s\n' 'git diff' 'git log' 'git show' 'git blame'
  if [[ -n "${TYPECHECK_COMMAND:-}" ]]; then
    printf '%s\n' "${TYPECHECK_COMMAND}"
  fi
  if [[ -n "${TEST_COMMAND:-}" ]]; then
    printf '%s\n' "${TEST_COMMAND}"
  fi
}

# jq emits a JSON array of strings, which is also a valid TOML array of basic
# strings. Going through jq keeps quotes and backslashes in the commands escaped.
ALLOWED_JSON="$(allowed_prefixes | jq -R . | jq -s -c .)"

cat > "${POLICY_FILE}" <<EOF
# Generated by parsleyhealth/github-composite-actions pr-review/gemini-pass.
# User tier (base priority 4) so these rules outrank the --yolo allow-all default.

[[rule]]
toolName = ["write_file", "replace"]
decision = "deny"
priority = 900
denyMessage = "This is a read-only review. Do not modify the working tree."

[[rule]]
toolName = "run_shell_command"
commandPrefix = ${ALLOWED_JSON}
decision = "allow"
priority = 500

[[rule]]
toolName = "run_shell_command"
commandRegex = '[\s\S]*'
decision = "deny"
priority = 100
denyMessage = "Only git inspection and the configured typecheck/test commands are allowed."
EOF

echo "Wrote ${POLICY_FILE}:"
cat "${POLICY_FILE}"
