name: "Slack Job Status"
description: "Creates outputs based on the workflow's job status usable with [voxmedia/github-action-slack-notify-build](https://github.com/voxmedia/github-action-slack-notify-build)"
inputs:
  job-description:
    description: "Description of job to display in Slack notification"
    required: false
    default: ""
outputs:
  status:
    description: "Text status of job for notification"
    value: ${{ steps.slack-status.outputs.status }}
  color:
    description: "Color of notification based on job status (success/failure/cancelled)"
    value: ${{ steps.slack-status.outputs.color }}

runs:
  using: "composite"
  steps:
    - name: Get Job Status Slack Outputs
      id: slack-status
      shell: bash
      run: |
        [ "${{ job.status }}" = "cancelled" ] && \
          echo "::set-output name=color::warning" &&  \
          echo "::set-output name=status::${{ inputs.job-description }} Cancelled"
        [ "${{ job.status }}" = "success" ] && \
          echo "::set-output name=color::good" && \
          echo "::set-output name=status::${{ inputs.job-description }} Success"
        [ "${{ job.status }}" = "failure" ] && \
          echo "::set-output name=color::danger" && \
          echo "::set-output name=status::${{ inputs.job-description }} Failed"
        exit 0
