name: GitHub Tag Update

on:
  release:
    types:
      - published
      - edited

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: tag
        run: |
          echo "::set-output name=version::$(cat version.txt | awk -F '=' '{ print $2 }')"

      - uses: fischerscode/tagger@v0.1
        with:
          prefix: v
          tag: v${{ steps.tag.outputs.version }}
