name: GitHub Tag Update

on:
  release:
    types:
      - published

jobs:
  actions-tagger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: validate-version
        run: |
          if [[ ! -s version.txt ]]; then
            echo "Error: version.txt file is empty or doesn't exist."
            exit 1
          fi

      - id: tag
        run: |
          echo "version=$(cat version.txt | awk -F '=' '{ print $2 }')" >> $GITHUB_ENV

      - name: Run fischerscode/tagger
        if: ${{ success() }}
        env:
          VERSION: ${{ env.version }}
        run: |
          if [[ -z "${{ env.VERSION }}" ]]; then
            echo "Error: Failed to get the version from the previous step."
            exit 1
          fi
          echo "Running fischerscode/tagger with version v${{ env.VERSION }}"
